### ISSUE TITLE
As a user I want to use tamanoir rest api via internet instead of installing server side on own pc

### ISSUE THREAD

**Issue by amalieiev** [amalieiev/tamanoir#12]
please deploy server to any free host (like heroku or whatever you wish) to make it available 24/7

**Comment by sergiyblazhievsky** [comment]
Amazon instance is up and running. It can be accessed like this
http://ec2-52-89-60-244.us-west-2.compute.amazonaws.com:8080/tamanoir/rest/connections?include=public
