### ISSUE TITLE
regresion on server side

### ISSUE THREAD

**Issue by amalieiev** [amalieiev/tamanoir#9]
ClassCastException

**Comment by sergiyblazhievsky** [comment]
Fixed
Commit gone in pull request to Yaroslav
New JSON object slightly differ from what was before 
Was:
- items
- \- table
- \- - table name
  Now:
- elements
- \- table
- \- - <element type> (element\group\reference) - for the tables it will be group
- \- - - table name

**Comment by amalieiev** [comment]
please let me know when these changes appear in Yaroslav's repo

**Comment by amalieiev** [comment]
recursive and expand features doesn't work
